apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: inventary-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventary
  goals:
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 30
  constraints:
    global:
      minReplicas: 2
      maxReplicas: 8  # Escalamiento agresivo para alta demanda
    containerControlledResources: [ memory ]
    container:
      - name: '*'
        requests:
          minAllowed:
            memory: 2Gi
          maxAllowed:
            memory: 6Gi
  policy:
    updateMode: Auto
